@startuml BooksDiagram
abstract class TheMovieDbClient {
  + popular(type: string, page: integer): JSON
  + by_id(type: string, id: integer): JSON
  + by_title(type: string, title: string,page: interger): JSON
  + season_by_number(show_id: integer, season_id: integer): JSON
  + episode_by_number_in_season(show_id: integer, season_id: integer, episode_id: integer): JSON
  - fetch_response(response: JSON): JSON
  - send(query: string): JSON
  - add_image_irl(content: object): JSON
}

interface TheMovieDbQueryBuilder {
  + where(field: string, value: any): TheMovieDbQueryBuilder
  + search_mode(enabled: boolean): TheMovieDbQueryBuilder
  + popular(enabled: boolean): TheMovieDbQueryBuilder
  + type(type: string): TheMovieDbQueryBuilder
  + season(season: integer): TheMovieDbQueryBuilder
  + episode(episode: integer): TheMovieDbQueryBuilder
  + valid?(): boolean|Error
  + build(): string
}

TheMovieDbClient ..> TheMovieDbQueryBuilder

@enduml