version: "3.3"
services:
  web:
    build:
      context: .
      args:
        editor: "nano"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - RAILS_ENV=development
